# how much many do you want to raise?
# putting 0 here will disable this functionality
gift_registry_goal: 5000.00

# set admin password
password: secret

# paypal ipn information
paypal_button_id: PAYPALHOSTEDBUTTONID